
language: java

jdk:
  - oraclejdk8
  - oraclejdk7

before_install:
  - apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

install:
  - ssh-keygen -f ~/.ssh/id_rsa -t rsa -N '' -b 4096
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - chmod 700 ~/.ssh/authorized_keys

addons:
  ssh_known_hosts:
  - 127.0.0.1
  - localhost

script:
  - ant coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
